version: '2'

services:

  data:
    image: mongo
    ports:
      - "27017:27017"

  api:
    build: Api
    ports:
      - "8888:8888"
    links:
      - api

  web:
    build: Web
    ports:
      - "8080:80"
